export const CHAT = [{
    userId: '1',
    userName: 'Le receptionniste',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '2',
    userName: 'Le client',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '1',
    userName: 'Le receptionniste',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '2',
    userName: 'Le client',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '1',
    userName: 'Le receptionniste',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '2',
    userName: 'Le client',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
}, {
    userId: '1',
    userName: 'Le receptionniste',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '2',
    userName: 'Le client',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '1',
    userName: 'Le receptionniste',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '2',
    userName: 'Le client',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '1',
    userName: 'Le receptionniste',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
},
{
    userId: '2',
    userName: 'Le client',
    translate: '',
    text: {
        shindzuani: '',
        shingazidja: '',
        shimwali: '',
        shimaore: '',
    },
}];
